const registerTypes = {
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_RESET_SUCCESS: 'SIGN_UP_RESET_SUCCESS',
};

export default registerTypes;
