const voteTypes = {
  FETCH_VOTE_START: 'FETCH_VOTE_START',
  FETCH_VOTE_FAILURE: 'FETCH_VOTE_FAILURE',
  FETCH_VOTE_SUCCESS: 'FETCH_VOTE_SUCCESS',
  CLEAR_VOTE: 'CLEAR_VOTE',
};

export default voteTypes;
